### ISSUE TITLE
useQuery should "open" more

### ISSUE THREAD

**Issue by ducan-ne** [vadimdemedes/draqula#4]
Hello
I thinks structure/syntax of the `useQuery` should like this

```javascript
const [data, {isLoading, error}] = useQuery(TODOS_QUERY);
const [mutate] = useMutation(PING_MUTATION);
```

This will make `useQuery` varname more customizable. Ex:
```javascript
const [pages] = useQuery(TODOS_QUERY);
const [posts] = useQuery(TODOS_QUERY);
const [createPost] = useMutation(PING_MUTATION);
```

**Comment by andrewangelle** [comment]
@quaj 

you can simply alias the variable name

```javascript
const {data: nameItWhateverYouWant} = useQuery(query)
```

**Comment by ducan-ne** [comment]
What i mean is change `{data}` to `[data]`, it's more simpler

**Comment by ducan-ne** [comment]
My opinion is that `data` is common variable name, relly excessive if every time we need alias `data`
Move to array will create a habit that use a strict `data` varname. Like: pages, users, posts, sure that `data` can be use

However, I think it will prevent awesome auto complete while using typescript
But it'll nice with javascript

**Comment by vadimdemedes** [comment]
I had `useQuery` and `useMutation` return an array initially, but when I showed it to my friend, we ended up arguing what should come first. Everyone has different opinions, so I figured that returning an array isn't ideal.

That's why both hooks return an object. If you need to rename `data`, chances are you have more than one query in the same component. In that case, you'll need to rename `isLoading` and `error` as well, because these should be taken into account as well. This version might be more readable:

```js
const postsQuery = useQuery(POSTS_QUERY)
const commentsQuery = useQuery(COMMENTS_QUERY)
```

**Comment by ducan-ne** [comment]
> I had `useQuery` and `useMutation` return an array initially, but when I showed it to my friend, we ended up arguing what should come first. Everyone has different opinions, so I figured that returning an array isn't ideal.
> 
> That's why both hooks return an object. If you need to rename `data`, chances are you have more than one query in the same component. In that case, you'll need to rename `isLoading` and `error` as well, because these should be taken into account as well. This version might be more readable:
> 
> ```js
> const postsQuery = useQuery(POSTS_QUERY)
> const commentsQuery = useQuery(COMMENTS_QUERY)
> ```

thanks
