### ISSUE TITLE
Question about background refetch implementation

### ISSUE THREAD

**Issue by samselikoff** [vadimdemedes/draqula#8]
👋 Hi Vadim! Nice work on this lib!

I've been learning hooks and am actually trying to implement something similar to draqula myself. I was working on a background refetch implementation, just like your library has.

To achieve this I needed to make sure the initial data fetch only went out if the cache was empty, similar to your effect here:

https://github.com/vadimdemedes/draqula/blob/master/src/useQuery.ts#L120-L129

The problem is React gave me a lint warning that my effect had missing dependencies, and I pulled down your code and noticed it said the same thing.

The problem is if you add `cachedData` to the dependencies list, the effect will fire again, which is not what you want. You only want to fire the effect once, and have it change behavior based on the state of the cache. If you add `cachedData` I can't figure out a way to reproduce the background refetch behavior.

Curious if you had any insight here! I'm new to React so I'm not sure if ignoring the lint errors is okay or if it means there's something wrong.

Great job again on the lib 😀

**Comment by vadimdemedes** [comment]
Thank you!

The reason I don't have `cachedData` as a dependency of https://github.com/vadimdemedes/draqula/blob/master/src/useQuery.ts#L120-L129, is because `fetch` is already in the list of dependencies there. And `fetch` will be "refreshed" if `cachedData` changes, because it's in the dependencies of `fetch` here: https://github.com/vadimdemedes/draqula/blob/master/src/useQuery.ts#L77. So every time `cachedData` changes, `fetch` changes, and then https://github.com/vadimdemedes/draqula/blob/master/src/useQuery.ts#L120-L129 runs :)

**Comment by vadimdemedes** [comment]
I wouldn't rely on hooks lint plugin at all times, because I'm using a custom `useDeepDependencies` hook anyway, to add support for comparing values using deep equality.

```js
useQuery(QUERY, { myVariable: 'value' })

// Will keep firing infinitely, because `variables` object is reconstructed on every render
useEffect(..., [query, variables])
```

**Comment by samselikoff** [comment]
> So every time cachedData changes, fetch changes, and then https://github.com/vadimdemedes/draqula/blob/master/src/useQuery.ts#L120-L129 runs :)

I know – but I think this means there's a problem with the effect. I think avoiding the lint warnings is a problem and means the effect isn't fully declared. (I read at some point deps may be automatically added by React.)

I think you could add more logic to the effect so it (a) has all its dependencies but (b) only runs when you want it to. Pseudocode:

```js
useEffect(() => {
  if (oldQuery !== newQuery) {
    setIsLoading(cachedData === null);
    setError(null);
    setData(cachedData);

    const abortController = new AbortController();
    fetch({ signal: abortController.signal });

    return () => abortController.abort();
  }
}, [fetch, cachedData, oldQuery, newQuery]);
```

You could make the `oldQuery !== newQuery` check anything you need it to, maybe using your deepEquality check or something else. But this way React can rerun this hook again and again but the fetch will only run when you want it to. What do you think?

(Again I'm new to all this but trying to learn useEffect and still finding it confusing! I don't think the core team would add the eslint plugin if it should be ignored though.)

**Comment by vadimdemedes** [comment]
Ah I see what you mean. I actually left `cachedData` out on purpose, so that only first value is checked in that effect. It's done to show loading indicator only if there's no cached data display already to prevent content flickering (show cached content -> loading indicator -> show loaded content).

I agree this logic is a bit confusing and I'm definitely planning to go back to it and see how I can clear it all up.

**Comment by vadimdemedes** [comment]
Cleaned up `useQuery` in https://github.com/vadimdemedes/draqula/commit/ed6c1e05def96b7f7d583acaafbac39b0194d063.
